### ISSUE TITLE
Reprint request~

### ISSUE THREAD

**Issue by gougocoffee** [aesoppppp/DoubleJump#1]
Dear Author:
         Can I reprint this plug-in to China's largest world forum? Thank you very much.
         BanZang

**Comment by aesoppppp** [comment]
It's free to use this plugin anywhere. But not yet. The plugin needs some modifications. They collide with other permissions, So I will fix them tomorrow.

**Comment by dongmin-dev** [comment]
> Dear Author:
> 
>          Can I reprint this plug-in to China's largest world forum? Thank you very much.
> 
>          BanZang


It's free to use this plugin anywhere. But not yet. The plugin needs some modifications. They collide with other permissions, So I will fix them tomorrow.

**Comment by gougocoffee** [comment]
Thank you very much. Come on, you did a good job! Let's learn your excellent code!

**Comment by dongmin-dev** [comment]
> Thank you very much. Come on, you did a good job! Let's learn your excellent code!

I forgot to answer you sry. 

You can share this source anywhere if you add my name on the post. And add 'This plugin uses PlayerMoveEvent. So it may collide with other flying plugin.' 

Thanks a lot for waiting and bless you 😊

+ I will try to fix the collision and jump amount at next update.

**Comment by gougocoffee** [comment]
❤Dear aesoppp:
I like your plug-in very much, because it's super. Your name and GitHub's source have been marked. Thank you for your approval. I hope you can do better!
BanZang
